### PR TITLE
2 create streamlit frontend mock

### PR DESCRIPTION
**Pull request by lucasiragusa**
This implements a basic mock front end on streamlit. Not yet connected to any backend logic

### CODE REVIEW

**Review by Zaubeerer — APPROVED** [review]
Looks good to me!

Looking forward to discussing the app next week :)

**Comment by lucasiragusa** [comment]
Unfortunately I was not able to resolve these conflicts and this is now such an old branch that I am wondering if I should even merge it at all. 

I will continue to work on other branches and send other pull requests and I suggest we take the next in person meeting to merge.

**Comment by Zaubeerer** [comment]
Sounds good to me 👍

**Comment by lucasiragusa** [comment]
I think I was able to resolve the conflicts and merge, however I think I accidentally skipped the review step as I did everything from the terminal. 

Can you please check if any review is needed of this merge?

**Pull request merged**
