### PR TITLE
6 flight serialization refactoring

### PR DESCRIPTION
**Pull request by Zaubeerer**
Hey @lucasiragusa, I just refactored the code a bit by:
- running ruff format on the files
- removing the sys.path workaround
- adding pixi dependency management (you can check out pixi or keep using your current setup, as you like)

Now, you can run `pytest .` and it should not return any errors anymore.

However, you didn't actually write any test in the test file.

Therefore, I suggest that we write some first tests in this PR, merge it into 6 and then continue the #19 .

### CODE REVIEW

**Review by Zaubeerer — COMMENTED** [review]
Just commenting to mark viewed files.

**Comment by lucasiragusa** [comment]
Hi Robin, 

As discussed yesterday, I practiced adding some test cases and it seems to work with Pixi. I think the next step you mentioned was to merge this branch into the "non refactored" branch 6. 

I will work this week on understanding how profiling works. Before I do that I need to make sure the rest of my environment except Pixi also works again, since as you saw yesterday I am no longer able to run the main. 

Let me know if okay to merge this branch. 

Thanks!

**Review by Zaubeerer — COMMENTED** [review]
Looks good to me!

**Comment by Zaubeerer** [comment]
Yes, as discussed, let's merge this PR.

As you can see above, this PR merges my pixi refactoring suggestions along with your created tests into the `6-flight-serialization` branch.

image


So, you can simply click "Merge pull request".

Then, check out the `6-flight-serialization` branch and sync it with origin by simply clicking the "sync button" on the lower left.

**Comment by lucasiragusa** [comment]
I made some additional small refactoring based on some initial findings from the profiling, see https://github.com/lucasiragusa/landingpermit_app/issues/20. 

I did commit and push, I hope that by merging now it will merge the latest commit and not the previous one :)

**Pull request merged**
